# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bastien Jacquet's Website
email: bastien.jacquet@kitware.com
description: > # this means to ignore newlines until "baseurl:"
  Bastien Jacquet's Website about Computer Vision, 3D reconstruction, Image Analysis
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-22202417-2

social_links:
  - Kitware: http://www.kitware.com/company/team/jacquet.html
  - GitHub: https://github.com/bastienjacquet
  - LinkedIn: https://www.linkedin.com/in/bastienjacquet/
  - Research Gate: https://www.researchgate.net/profile/Jacquet_Bastien
  - Academia: https://ethz.academia.edu/BastienJacquet
  - DBLP: http://www.informatik.uni-trier.de/~ley/pers/hd/j/Jacquet:Bastien.html
  - Google Scholar: https://scholar.google.com/citations?user=4ntv_BgAAAAJ
# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
